apiVersion: v1
kind: ConfigMap
metadata:
  namespace: lnmp
  name: nginx-wp-config
data:
  nginx.conf: |-
    user  root;
    worker_processes  auto;

    error_log  /var/log/error.log  info;
    pid        /var/run/nginx.pid;

    events {
        use epoll;
    }

    http {

        include       mime.types;
        default_type  application/octet-stream;

        log_format  main '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/access.log main;
        sendfile        on;
        keepalive_timeout  65;

        server {
            listen 80;
            root /var/www/wordpress;
            index index.php index.html;

            location ~ \.php$ {
                root /var/www/wordpress;
                fastcgi_pass wordpress-php:9000;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
            }
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: wordpress-nginx
    qcloud-app: wordpress-nginx
  name: wordpress-nginx
  namespace: lnmp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wordpress-nginx
      qcloud-app: wordpress-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: wordpress-nginx
        qcloud-app: wordpress-nginx
    spec:
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        image: ccr.ccs.tencentyun.com/chenyong/nginx:wp
        imagePullPolicy: Always
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: config
          readOnly: true
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx-wp-config
        name: config

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-nginx
  namespace: lnmp
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp-80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: wordpress-nginx
    qcloud-app: wordpress-nginx
  sessionAffinity: None
  type: LoadBalancer
