apiVersion: v1
kind: ConfigMap
metadata:
  namespace: lnmp
  name: php-wp-config
data:
  wp-config.php: |-
    <?php
    /**
     * WordPress基础配置文件。
     *
     * 这个文件被安装程序用于自动生成wp-config.php配置文件，
     * 您可以不使用网站，您需要手动复制这个文件，
     * 并重命名为“wp-config.php”，然后填入相关信息。
     *
     * 本文件包含以下配置选项：
     *
     * * MySQL设置
     * * 密钥
     * * 数据库表名前缀
     * * ABSPATH
     *
     * @link https://codex.wordpress.org/zh-cn:%E7%BC%96%E8%BE%91_wp-config.php
     *
     * @package WordPress
     */
    
    // ** MySQL 设置 - 具体信息来自您正在使用的主机 ** //
    /** WordPress数据库的名称 */
    define( 'DB_NAME', 'wordpress' );
    
    /** MySQL数据库用户名 */
    define( 'DB_USER', 'root' );
    
    /** MySQL数据库密码 */
    define( 'DB_PASSWORD', '123456' );
    
    /** MySQL主机 */
    define( 'DB_HOST', 'wordpress-mysql' );
    
    /** 创建数据表时默认的文字编码 */
    define( 'DB_CHARSET', 'utf8mb4' );
    
    /** 数据库整理类型。如不确定请勿更改 */
    define( 'DB_COLLATE', '' );
    
    /**#@+
     * 身份认证密钥与盐。
     *
     * 修改为任意独一无二的字串！
     * 或者直接访问{@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org密钥生成服务}
     * 任何修改都会导致所有cookies失效，所有用户将必须重新登录。
     *
     * @since 2.6.0
     */
    define( 'AUTH_KEY',         '%b)XKW5cH+7$k{S)mlQkN[Y=Tysom}3qnP$+u523PLnM_j|mce(faJj/=1 ote*c' );
    define( 'SECURE_AUTH_KEY',  'kvQi2y(B!%(k4C7dOof FiP55+V0pxhn<gU2N_/g<~rPwEfTIg+8]]r)DLEWCLMd' );
    define( 'LOGGED_IN_KEY',    'l3AJ:Bm_(q2.HzE7QIk<L&j:Co`U61lZMW`A@)n:EAct$7}4_^VU#iYH^b]<d`@T' );
    define( 'NONCE_KEY',        'kY~+.r.fm5{1D76C>c9V0loPx~Z03@H[%V]j?`p)+k.clE,Z9(hHG^w06`/[BW3P' );
    define( 'AUTH_SALT',        '4!{TyU-&D?i_pXm.M*KX}HA:8UZ,O8z=$+]_YxqmX4To?&ikjn]?Sq*/:/.n[s8,' );
    define( 'SECURE_AUTH_SALT', 'c7#-A>jCzU$wDBqIl9P6BSk`]bp-QZ0%=mQ12W-cBP!t:I{gk6M}VIC_bTVIQ>ts' );
    define( 'LOGGED_IN_SALT',   ' *U+-p<C(jGESxE[_J,M^K8Y~ornDR7=uGz<PHpoKMADjpee5PQ1L:9*)peg*A<-' );
    define( 'NONCE_SALT',       'H,e5vR%~2E>p_3(&WYPKWT/}5w@zJ k#i&$jm/7>dYZkjK@]Jx?K$(tL2_Kk~lYw' );
    
    /**#@-*/
    
    /**
     * WordPress数据表前缀。
     *
     * 如果您有在同一数据库内安装多个WordPress的需求，请为每个WordPress设置
     * 不同的数据表前缀。前缀名只能为数字、字母加下划线。
     */
    $table_prefix = 'wp_';
    
    /**
     * 开发者专用：WordPress调试模式。
     *
     * 将这个值改为true，WordPress将显示所有用于开发的提示。
     * 强烈建议插件开发者在开发环境中启用WP_DEBUG。
     *
     * 要获取其他能用于调试的信息，请访问Codex。
     *
     * @link https://codex.wordpress.org/Debugging_in_WordPress
     */
    define('WP_DEBUG', false);
    
    /* 好了！请不要再继续编辑。请保存本文件。使用愉快！ */
    
    /** WordPress目录的绝对路径。 */
    if ( ! defined( 'ABSPATH' ) ) {
            define( 'ABSPATH', dirname( __FILE__ ) . '/' );
    }
    
    /** 设置WordPress变量和包含文件。 */
    require_once( ABSPATH . 'wp-settings.php' );
    
